apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:mkHfKyLB4teraG+Z6CFPpfsYSU4fhjwsM3/hQlsrGT2gEP9Y,iv:20JsJTh3keoBJmSp2iEYGLx6pePFLv4txu6bN3S25B8=,tag:bJkXajDJgM8rb/wLgvv91g==,type:str]
    credentials.json: ENC[AES256_GCM,data:YQkYlnSlq/+IBh1XZfO6dFIDjcUAcM1UyxfAlOZrF7QOHl6UHNGf9eXjnZ4RKI9UTwh3R78SqOAo+BNvIHs3l2cGzfSwlL6scMSzBGKL+htXrXbzJQppsquGQ8gg8bPLTEL6d1UIdbyK57cU4fR3B96W1/BHZT7iesaZIj3kecPncgHBx6uVJVmcy7VnAjSZN8IGPZ5fFxIRsTBXHWRIo7qtahzjokH91LrcQOa5VQ==,iv:vAY6h7IpdJjWk9m3//SJh5pBXd6NYB1QTgG1r/3Upao=,tag:2tuvAszVE94cSBXcEeSIUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd3j7yf8dzs8vsy8n6kkwkpd4v2f7a6ug84pphvh87zxecxkv5gsgfjsg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNjBSSVlHTHBsdFVVcjE0
            Wng0MkJLMWVXT2ptYjRCbmRBM2Q0QytKRlJFCjRBY09XQVhoZDY2MmdkbFMwVXpp
            cS91QzlZajQvQkU0ZjNXNy9WLzlJK1EKLS0tIEpSdnR5SitBNFNyK0QvaHB4U2Vo
            WG1pcHlYbVBzSGRQcnBJaXpxbmtveUkKz/cnVv2ctNOWD9GUjhMuGxP3YwnDHGko
            LnRTx0IUaPRbBhl0ywkkWtkg5lJ97RM5bhVX1cGxQXDNGFHFGcAesQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T18:46:47Z"
    mac: ENC[AES256_GCM,data:P84WQGtOrabrL7yssBF5eFu2VkAeQ2jFORSbCVTT1/Sdl3ZQXiYANziKlTFWfD/EW1Q6OpAn0YVcxotEO6wfP9otOckIS4k20sURiM+cjT99xuk/sDzrVcN0zycFE7d4GEf8Elj/ha4HxVlAZgI4alSppdoAacDHc2uIVCg/XZM=,iv:XMbDIv2HTvS4vqprQnrktgTwAzY7jFy/B55/kcQI9g4=,tag:ZQZel7BDmfpqgU0L7upqlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
