apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5L3+vWNyJnv+IJK2/2klr9I+obrYNQRwyVgND9G6039IJRQnxxEVnw==,iv:IxrKWg4ittKTIazo7eWo/w1rT50lAnkdaOHHBvR5+CM=,tag:HzhjT9i2CXErmff+PxH8/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd3j7yf8dzs8vsy8n6kkwkpd4v2f7a6ug84pphvh87zxecxkv5gsgfjsg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcHlYZWxvZ3B4VUUraGVC
            MTlzU3hkRi9uWGh0TjEzTEdOR2pJajUxZEFJCnNlb3dRb01Hb3krdTVlTGRHT0FR
            cmtVc1g1Rm8xLzNqcWVsdG9aYU5YL2sKLS0tIEVKWkExRXRmMUd2ODAwTzF0TlBM
            ZFNrdGpuamhsUFB6WXNGZDRBbkJBdmMK/uP2W5phkp2cHRkJcDIOyRE4Ru8QumhF
            jwJwHy40fCvRYqEt192josLHzAihdAN386pfRTkDDbr2sKP2dh6/jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T19:42:08Z"
    mac: ENC[AES256_GCM,data:YEowrWpEf6zvb8smye/x9foiwJIZ460N3feOk1egvZRnHjo4Zox7o5WcDm2Va7Nrz7SaHIJmc/ppDX2WnoE/c5B8peYVP+38lduFVGj/OA8tpmuAZSGuwogrRO6k9h6uv44zON2joNa2D7iwGYabeRYWk3UPLOVNH3OCGKcCoZU=,iv:5Cm1Vk2XM1+9EH1nWBc5KR+wnvgMv+o58dgfYylSx1Q=,tag:UFbL2JEVTPauUR+WAuazdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
