apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:iLwyY+CGXDOTQXE=,iv:fb7sHDyz4ngX5Gf42MptQlJ2oVQNAhmzo5MzCddYClQ=,tag:fCJ2FJHrRJ8vmgZdDCWXcg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9DBljRYzp2GXn6vqX/+QSkAlIEu2rSLCQA==,iv:s5YmErdOLQ62axy/6iClAZUhKJrpZGAd/FvYmxuvR/E=,tag:eZ2r4E5rg/IDuX046n17Aw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:USI2ee63In9UnSxH0MNoZPTStr61pkuVkBJEFbJo83gsXX3x,iv:L/RRn+SigzeGMUFdO3rmQP9vM9prrSyCWx1Kx72qzTE=,tag:WwuPf9wA6N2xCDTY2G9bgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd3j7yf8dzs8vsy8n6kkwkpd4v2f7a6ug84pphvh87zxecxkv5gsgfjsg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdmwvTzVqRDYvTzJpWmZG
            UjZiU3ArNG52Q0xqZFc4clNxZ2VNWTRyOERVCng5K3VIYTBRdlczSG5iUmw0dC84
            Rk1hR1Jkbm1GNFV3NXBIbmw1TEFxM1UKLS0tIFprdGZlcW1EMDdjaFJ2YXA4Rnc5
            YU1vZmFaTE5iazBIRnZiSVV6Ky9USHMKquqEGArWkrrS8B1b51vbWNsORgPIsE6t
            HarDxIbriPBCvJM3P9o5kRoVpKRPsRxED/xWtBSYqLgl3PnC9HNKLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T19:10:44Z"
    mac: ENC[AES256_GCM,data:mGeR9ldu8vHFRkZMyv6OLUmjQn6t8dzVmexhGhsMaqfI2ABBIUmguHaES5gfc8mYWTWgMgKn9yvgvrmP0AiIkk0mUMpILjvf6z0Ei1qHDoAz3Iht2SengqI3UA71MO/wAJve/5q5JIb/XRPEJZ9Gus3Q7J3hT7Iv3E2/R0sVZ9I=,iv:rC/2tdKYJXSAZrSjitLjm+WUs3Cpag2hbYr7Du8sw8E=,tag:U6CI/+JGiGGidRRkSKGTvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
