apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:iyYeSVeGI3P4IvWMI26/bLJy04JqefUimEnF7QRvqA0=,iv:WtaVCX9y4EnuJo1YXpvGfxvSQkhAXZ7vcWNzWl1tZ8k=,tag:CwaWBD54o6ZaiQXC6OzTdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd3j7yf8dzs8vsy8n6kkwkpd4v2f7a6ug84pphvh87zxecxkv5gsgfjsg5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMlhoSlpoUVpsT0pialZF
            bkV1L1ZxOVRjVkI4RWtqOFgzcG1Ob2RaT1Y4CjBzeGQxWFlHVUgveXRjMFhFbEhp
            WjJqSXdWSDhoclYydW9jeVBvT3pYdkkKLS0tIHV4MlU5RFpSZko5bFY5TWxkb2w2
            YWIzdDRxUFFBUzNjVzBiazNBTkEwMDAKNUKShKJ5CCkJC5d67pmT2TgRbcTLTAwX
            r9cXH1y+/7ZtexZ9TXjDCYsWGC48MvxruffGgcLZPKN+WDn1mLLaYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T18:46:47Z"
    mac: ENC[AES256_GCM,data:wQNHTZJ3OoyH9cv/icGwCRW/7HVbxwg2ldeosJWVxt5Ih9q1odJs+rPAzyiUmMcZiId3CPaLX/I4SetXlJ0HoAC90kL84mgvX1rqgvlG36FP02oWXbXIuvh1yLlfMe7f3OHmjDN53/0dVyudW2hHQEt2BNUkMJFWA1HQf0reyVA=,iv:9mX44JZQos1KSz1K0YztgYl52ngN8ZCH6zlV7QjUhKQ=,tag:7IytS3yis9u3pfxDhYDOWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
